# Generated by Django 2.2.3 on 2019-07-18 16:31

from django.db import migrations, models
import django.db.models.deletion
import minimalist_cms.cms_content.models.fields.container


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_content', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('is_home', models.BooleanField(default=False)),
                ('container_body', minimalist_cms.cms_content.models.fields.container.ContainerField(container_name='container_body', editable=False, limit_choices_to={'name': 'container_body'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_body', to='cms_content.Container')),
                ('container_header', minimalist_cms.cms_content.models.fields.container.ContainerField(container_name='container_header', editable=False, limit_choices_to={'name': 'container_header'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_header', to='cms_content.Container')),
                ('parent_page', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_set', to='cms_pagetree.Page', verbose_name='Parent page')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='de', max_length=8, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, verbose_name='Slug')),
                ('path', models.CharField(default='', editable=False, max_length=1000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_set', to='cms_pagetree.Page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page translation',
                'verbose_name_plural': 'Page translations',
                'ordering': ['language'],
                'unique_together': {('page', 'language')},
            },
        ),
    ]
