# Generated by Django 2.1.10 on 2019-07-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pagetree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Level'),
        ),
    ]
