# Generated by Django 2.1.10 on 2019-07-19 14:06

from django.db import migrations
import django.db.models.deletion
import minimalist_cms.cms_content.models.fields.container


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pagetree', '0002_page_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='container_body',
            field=minimalist_cms.cms_content.models.fields.container.ContainerField(container_name='page_body', editable=False, limit_choices_to={'name': 'page_body'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_body', to='cms_content.Container'),
        ),
        migrations.AlterField(
            model_name='page',
            name='container_header',
            field=minimalist_cms.cms_content.models.fields.container.ContainerField(container_name='page_header', editable=False, limit_choices_to={'name': 'page_header'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_header', to='cms_content.Container'),
        ),
    ]
