# Generated by Django 2.2.3 on 2019-07-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Container',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('element_type', models.SlugField(max_length=100, verbose_name='Type')),
                ('container', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_content.Container', verbose_name='Container')),
                ('parent_element', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element_set', to='cms_content.Element', verbose_name='Parent element')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Container',
                'ordering': ['container', 'parent_element', 'position'],
            },
        ),
    ]
