# Generated by Django 2.1.10 on 2019-07-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms_content', '0003_auto_20190719_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['position'], 'verbose_name': 'Element', 'verbose_name_plural': 'Element'},
        ),
        migrations.AddField(
            model_name='container',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type'),
        ),
        migrations.AddField(
            model_name='container',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
    ]
